Add modified html and css files
Frelly0/portfolio_project pull request #3
Opened 2023-06-02 18:06 UTC by Frelly0

Accomplishment

It is my personal portfolio project and i have added some new features in this repository and they are as following:

 . Added html file
 . Added css file

2023-06-02 19:44 UTC, shahadat3669 requested changes
Hi @Frelly0 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media2.giphy.com/media/Khi4ihXtrDpfnlZIXh/giphy.gif"/>

## Highlights
✅ No linters errors.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
-  Please it is unnecessary to comment out previously completed work in your portfolio. By uncommenting the previously successful work, you can showcase your progress and have a complete portfolio at the end of the module. Remember, each week you will be working on new tasks, and there is no need to comment on the work from previous weeks. Keeping the previous work visible will provide a comprehensive view of your development journey and allow others to see your growth over time.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-02 19:44 UTC, shahadat3669 commented on index.html
> +                </div>
Great job on the list of skills! However, there is a small adjustment that needs to be made to ensure proper linking functionality and semantic correctness. 

- [ ] Instead of using a div tag for the list, please use a ul tag to group the skills, and each skill should be wrapped in a li tag. :pray:
- [ ] Please add the necessary spacing, padding, and font styles for the items in the design. :pray:

| Your | Professional |
| --- | --- |
| ![image](https://github.com/Frelly0/portfolio_project/assets/55840999/00d96949-8635-43c5-b571-66f7f61d2493) | ![image](https://github.com/Frelly0/portfolio_project/assets/55840999/755784d1-4f68-4e9b-9a75-56d992608cce)   |

By making this change, you will enhance the semantic structure of the skills list.

2023-06-02 19:44 UTC, shahadat3669 commented on index.html
> +            </div>
Great job on creating the card! There are a few adjustments that can be made to improve its overall appearance and adherence to the design specifications:

- [ ] Replace the `<section>` tag with a more semantically appropriate tag, such as `<div>`, as the card does not represent a distinct section of content.
- [ ] Align the card in the center of the parent container by applying appropriate CSS styles, such as margin: auto or utilizing flexbox or grid properties.
- [ ] Add necessary spacing around the card to match the design specifications. You can use CSS margin or padding properties to achieve the desired spacing.
- [ ] Ensure that the card title has the correct styles as per the design, including font size, font weight, font family, line height, and letter spacing.
- [ ] Verify that the card includes the expected card image, as shown in the design. You may use the `<img>` tag or CSS background-image property to display the image.

By making these adjustments, you will ensure that the card aligns with the design and maintains proper styling and structure.


| Your | Professional |
| --- | --- |
| ![image](https://github.com/Frelly0/portfolio_project/assets/55840999/d2790a78-2686-40f2-b8e5-b7cd79e50317)  | ![image](https://github.com/Frelly0/portfolio_project/assets/55840999/300775b7-0fc4-42af-9ada-3695e272d42b)  |

2023-06-02 19:44 UTC, shahadat3669 commented on index.html
> +                    </div>
Overall, the code shows effort in implementation, but there are some areas where it does not align properly with the design. It is essential to pay attention to font styles, spacing, and alignment to ensure consistency with the design specifications. By addressing these aspects, the code can better reflect the intended design and enhance the overall user experience.
Please follow the design and make changes as much as possible.

| Your | Designe|
| --- | --- |
| ![image](https://github.com/Frelly0/portfolio_project/assets/55840999/b1769e37-92eb-4a61-811e-f6beba44ae46) | ![image](https://github.com/Frelly0/portfolio_project/assets/55840999/5ce25943-912a-44ed-a7c6-a286202e8602)  |

2023-06-02 19:44 UTC, shahadat3669 commented on index.html
> +                    <button type="submit" class="btn"><p>See project</p></button>
Commendable efforts have been made by you, there are some areas that require attention. The button implementation does not align with the design specifications as it lacks hover and active styles. Additionally, the embedded styles utilized do not adhere to the desired design. It is important to address these issues to ensure a consistent and cohesive visual presentation throughout the project.
![image](https://github.com/Frelly0/portfolio_project/assets/55840999/e2eae668-91ca-4e75-8290-89d766d107ed)

2023-06-02 19:44 UTC, shahadat3669 commented on index.html
> +    </section>
Great effort! However, the "Works" section does not adhere to the design specifications. To properly lay out the elements in the "Works" section, it is necessary to utilize both CSS Grid and Flexbox.

CSS Grid should be used in the main container that holds all the cards, while Flexbox should be used to arrange each individual card. By implementing this combination of CSS Grid and Flexbox, the layout of the "Works" section can align with the desired design.

2023-06-02 19:44 UTC, shahadat3669 commented on index.html
> +        <br><br>
Great job on the implementation! However, instead of using the `<br>` tag to create gaps between cards in the layout, it is recommended to use CSS properties like gap. This approach aligns with the design specifications and ensures a consistent and visually appealing gap between the cards. By replacing the `<br>` tags with appropriate CSS properties, you will achieve the desired design and improve the overall structure and readability of the code.

| Your | Designe|
| --- | --- |
| ![image](https://github.com/Frelly0/portfolio_project/assets/55840999/2e332fb8-8f26-4c34-b43f-19a372e126d9) | ![image](https://github.com/Frelly0/portfolio_project/assets/55840999/d5fa8088-5bd0-4b78-b1f5-f25536bd820b)  |

2023-06-02 19:44 UTC, shahadat3669 commented on index.html
> +    </section>
Great effort on creating the "About" section!:+1: However, there are several areas that need improvement to align with the design specifications. The images are not loading properly, and the font styles and spacing are not consistent with the design. 

It is crucial to reshape the entire section to ensure that it matches the design accurately. :pray:

Additionally, please ensure that the necessary images are available in the designated folder. :pray:

By closely following the design guidelines, you will enhance the overall appearance and user experience of the "About" section.:pray:

Please follow the design closely! :pray:

| Your | Designe|
| --- | --- |
| ![image](https://github.com/Frelly0/portfolio_project/assets/55840999/b354872e-c101-4f62-a5e2-02c65cbf0c3b) | ![About My Self (1)](https://github.com/Frelly0/portfolio_project/assets/55840999/425c993b-4b58-473b-887c-47ded0e9b6fc)  |

2023-06-03 00:59 UTC, Alusp requested changes
Hi @Frelly0 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![close](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)


 ## Highlights

- [x] No Linter Errors :green_circle: 
- [x] Good PR summary and title :green_circle: 
- [x] Professional Readme file used :green_circle: 
- [x] Good Github Flow :green_circle: 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-03 00:59 UTC, Alusp commented on index.html
> +                    <button type="submit" class="btn"><p>See project</p></button>
- [ ] [Required] Great job implementing the changes so far, :clap: However, as requested by the previous Reviewer the button implementation does not align with the design specifications as it lacks hover and active styles. Additionally, the embedded styles utilized do not adhere to the desired design. It is important to address these issues to ensure a consistent and cohesive visual presentation throughout the project. Please implement these changes in your styles. :slightly_smiling_face: 

![Buttons Designs](https://github.com/Frelly0/portfolio_project/assets/43528594/be2435b9-2a7a-4189-a712-a50a9eb75067)

2023-06-03 00:59 UTC, Alusp commented on index.html
> +        <br><br>
- [ ] [Required] As requested by the previous Reviewer, instead of using the `<br>` tag to create gaps between cards in the layout, it is recommended to use CSS properties like gap. This approach aligns with the design specifications and ensures a consistent and visually appealing gap between the cards. By replacing the `<br>` tags with appropriate CSS properties, you will achieve the desired design and improve the overall structure and readability of the code. The `<br>` tag in HTML is used to create a line break, forcing text or content to move to the next line within a paragraph. While it can be useful in specific cases, it is generally not considered good practice to use `<br>` tags excessively or for layout purposes.

2023-06-03 00:59 UTC, Alusp commented on style.css
> +}
- [ ] [Required] As requested by the previous reviewer, In order to lay out the elements in the "Works" section you should use CSS Grid and Flexbox combined (it is mandatory that you use both). Use CSS Grid in the main container that contains all of the cards and use Flexbox to lay out an individual card. As this is part of the project requirement, Please ensure to fix it. :slightly_smiling_face:

2023-06-03 00:59 UTC, Alusp commented on index.html
> +                    <h1>Multi-Post</h1>
- [ ] [OPTIONAL] Please ensure that you use only one `h1` tag in your entire HTML file, Adhering to good practices for heading structure and using the `<h1>` tag only once helps improve accessibility, SEO, and overall readability of your HTML documents. :slightly_smiling_face:

2023-06-03 07:56 UTC, brainconnect93 approved these changes
## Status: Approved :heavy_check_mark:

Hi @Frelly0, 👋 👋  

Your project is complete! Great job for following the project requirement🥇and implementing the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 


<img src="https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif" width="600px" height="300px">

## Good Points 👍

- Descriptive Pull Request title and summary. ✔️
-  Create the project cards and well aligned✔️
- Create the About me section with the tech stack ✔️
- Descriptive and professional README file ✔️
- Good use of Github flow ✔️

## Optional changes

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brainconnect93 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-03 07:56 UTC, brainconnect93 commented on index.html
> +                    <h1>Tonic</h1>
- [ ] [OPTIONAL] please try to implement all the optional changes you have in the previous reviews as they will help to have a better and complete project

1. Try to change where you have `h1` tag to other `hx` like `h2, h3, h4, ...` and limit the only h1 tag that should be in a webpage to the one you have in the heading and headline section. This is for semantics and SEO reasons.

2. Also I would implore you to bring back your heading and headline section which is the first milestone you worked on in this portfolio project inorder to have a complete project.
Thank you.

2023-06-03 08:01 UTC, merged